"""Example configuration. Copy the values you need into your shell environment.

Do NOT edit this file with real credentials and do NOT commit a filled-in copy.
``config.py`` reads every secret from the process environment and refuses to start
when a variable is missing or still holds an unresolved placeholder.

PowerShell:
    $env:SOLANA_NODE_RPC_ENDPOINT = "https://your-rpc-provider/your-key"
    $env:SOLANA_NODE_WSS_ENDPOINT = "wss://your-rpc-provider/your-key"
    $env:SOLANA_PRIVATE_KEY       = "<base58 encoded ed25519 secret key>"
    python trade.py

bash:
    export SOLANA_NODE_RPC_ENDPOINT="https://your-rpc-provider/your-key"
    export SOLANA_NODE_WSS_ENDPOINT="wss://your-rpc-provider/your-key"
    export SOLANA_PRIVATE_KEY="<base58 encoded ed25519 secret key>"
    python trade.py
"""

# Required. A Solana RPC HTTP endpoint. Provider API keys are billable
# credentials: keep them in the environment, not in a tracked file.
SOLANA_NODE_RPC_ENDPOINT = "https://your-rpc-provider/your-key"

# Required. The matching WebSocket endpoint, used for block subscriptions.
SOLANA_NODE_WSS_ENDPOINT = "wss://your-rpc-provider/your-key"

# Required. Base58 encoded 64-byte ed25519 secret key of the paying wallet.
# Anyone holding this key can drain the wallet. Rotate it immediately if it is
# ever committed, logged, or pasted into a chat.
SOLANA_PRIVATE_KEY = "<base58 encoded ed25519 secret key>"

# Optional. Trading parameters (defaults shown).
BUY_AMOUNT = "0.0001"
BUY_SLIPPAGE = "0.2"
SELL_SLIPPAGE = "0.2"
FEE_BUFFER_LAMPORTS = "10000"
PRE_BUY_DELAY_SECONDS = "15"
POST_BUY_HOLD_SECONDS = "20"
